import onnx
import logging
import onnx_graphsurgeon as gs

from onnx import ModelProto
from typing import Optional
from .onnx_graph import ONNXGraph
from ..utils import get_node_dict

logger = logging.getLogger(__name__)
class ONNXModel:
    '''
        onnx_model_proto: generated by onnx.load()
        digraph: directed graph for pattern matching and optimization
        gs_graph: graphsurgeon graph for fusion and manipulation
        gs_nodes: reserve gs nodes for further manipulation
    
    '''
    def __init__(self, onnx_model_proto: Optional[ModelProto] = None):
        self.onnx_model_proto = onnx_model_proto 
        self.digraph: Optional[ONNXGraph] = ONNXGraph(onnx_model_proto.graph) if onnx_model_proto else None
        self.gs_graph = gs.import_onnx(onnx_model_proto) if onnx_model_proto else None
        self.gs_nodes = get_node_dict(self.gs_graph) if self.gs_graph else {} 

    @classmethod
    def load(cls, path: str) -> 'ONNXModel':
        logger.info(f"Loading ONNX model from {path}")
        onnx_model_proto = onnx.load(path)
        return cls(onnx_model_proto)

    def save(self, path: str):
        if not self.onnx_model_proto:
            logger.error("Cannot save empty model.")
            return
        logger.info(f"Saving optimized ONNX model to {path}")
        onnx.save(self.onnx_model_proto, path)

    def get_digraph(self) -> Optional[ONNXGraph]:
        return self.digraph
    
    def get_gs_graph(self) -> Optional[gs.Graph]:
        return self.gs_graph
    
    def update_onnx_model_proto(self, new_model_proto: ModelProto):
        self.onnx_model_proto = new_model_proto

    def __repr__(self):
        return f"ONNXModel(ir_version={self.onnx_model_proto.ir_version if self.onnx_model_proto else None}, graph={self.digraph})"